spring:
  application:
    name: campus_life_guide
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/campus_trade?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      enabled: true
  # 邮箱
  mail:
    host: smtp.qq.com
#    port: 587
    port: 465
    username: 2584552106@qq.com
    password: csiuxetcwrxvecab
    protocol: smtp
    default-encoding: utf-8 #邮件内容的编码
    properties:
#      未选择发件人的默认发件人
      from: 2584552106@qq.com
      mail:
        #配置SSL 加密工厂
        smtp:
          ssl:
            #本地测试，先放开ssl
            enable: true
            required: true
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
#        socketFactory:
#          class: javax.net.ssl.SSLSocketFactory



  data:
    redis:
      host: localhost
      port: 6379
      password: 1234
      database: 0
      timeout: 300ms
      lettuce:
        pool:
          max-active: 50

server:
  port: 8080
  tomcat:
    max-swallow-size: 1000MB # 最重要的是这一行

logging:
  level:
    renko:
      jiang.campus_life_guide:
        mapper: debug
        service: info
        controller: info

mybatis:
  #mapper映射文件路径
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: renko.jiang.entity
  configuration:
    #驼峰命名自动映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


upload:
  path: D:\\image
  video: D:\\video

jwt:
  secret-key: jiangqiyue
  expiration: 604800000 # 7天

pagehelper:
  helper-dialect: mysql # 设置数据库方言，比如mysql, oracle等
  reasonable: true       # 启动合理化分页
  support-methods-arguments: true # 支持通过参数传递分页参数
  params: count=countSql


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    #自定义swagger前端请求路径,输入http:localhost:8080/swagger-ui会自动重定向到swagger页面
    path: /swagger-ui
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs  #swagger后端请求地址
    enabled: true   #是否开启文档功能
  group-configs: #分组配置,可配置多个分组
    - group: 'default'             #分组名称
      paths-to-match: '/**'        #配置需要匹配的路径
      packages-to-scan: com.cms    #配置要扫描包的路径,一般配置到启动类所在的包名
    - group: 'admin-api'
      paths-to-match: '/**'
      packages-to-scan: com.cms

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true    #开启knife4j,无需添加@EnableKnife4j注解
  setting:
    language: zh_cn   #中文
    swagger-model-name: 实体列表   #默认为：Swagger Models
  #开启Swagger的Basic认证功能,默认是false,开启后访问文档页面时会弹出用户名和密码输入框
  basic:
    enable: true
    # Basic认证用户名
    username: user
    # Basic认证密码
    password: 123456

